services:
  app:
    image: todo-front-product
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    env_file:
      - ./todo-frontend/.env.frontend
    # environment:
    #   -VITE_BACKEND_URL=
    expose:
      - "80"
    container_name: todo-front-product
  
  mongo:
    image: mongo
    ports:
      - 5456:27017
    env_file:
      - ./todo-backend/.env
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: 
    #   MONGO_INITDB_ROOT_PASSWORD: 
    #   MONGO_INITDB_DATABASE: 
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
    
  redis:
    image: redis
    ports:
      - 6379:6379 
    env_file:
      - ./todo-backend/.env
    # environment:
    #   - REDIS_URL
    volumes:
      - ./todo-backend/redis_data:/data
    command: ['redis-server', '--appendonly', 'yes'] # Overwrite the CMD

  server:
    image: todo-backend-production
    build: 
      context: ./todo-backend/
      dockerfile: Dockerfile
    volumes:
      - ./todo-backend/:/usr/src/app
    expose:
      - "3000"
    container_name: todo-backend-production
    env_file:
      - ./todo-backend/.env
    # environment:
    #   - REDIS_URL=
    #   - MONGO_URL=
    depends_on:
      - mongo
      - redis


  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8888:80
    container_name: todo-reverse-proxy
    depends_on:
      - app
      - server

# debug-helper:
#   image: busybox